apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dhakacart-redis-credentials
  namespace: dhakacart
  labels:
    app: dhakacart
    component: cache
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: dhakacart-redis-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        REDIS_HOST: "{{ .host }}"
        REDIS_PORT: "{{ .port }}"
        REDIS_URL: "{{ .redis_url }}"
  data:
  - secretKey: host
    remoteRef:
      key: dhakacart-dev-redis-credentials
      property: host
  - secretKey: port
    remoteRef:
      key: dhakacart-dev-redis-credentials
      property: port
  - secretKey: redis_url
    remoteRef:
      key: dhakacart-dev-redis-credentials
      property: redis_url